
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// Match Next.js's own precedence: .env first, then .env.local overrides it.
config({ path: ".env" });
config({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  // CLI schema operations (migrate/push/studio) go through the direct,
  // non-pooled connection — the pooler doesn't support the DDL/prepared
  // statement patterns these commands use. The generated Prisma Client
  // (runtime) independently reads `url` from schema.prisma's datasource
  // block, so app code still goes through the pooled DATABASE_URL.
  datasource: {
    url: env("DIRECT_URL"),
  },
});
